### PR TITLE
Fix `include`

### PR DESCRIPTION
**Pull request by amirouche**
fix: https://github.com/justinethier/cyclone/issues/494
requires: https://github.com/justinethier/cyclone/pull/496

### CODE REVIEW

**Comment by amirouche** [comment]
Example run:

```scheme
;; #> ./cyclone -COPT '-Iinclude' -CLNK '-L.' -A . -A ../tmp/ ../tmp/main.scm 
../tmp//foobar/base.c:112:10: fatal error: cyclone/types.h: No such file or directory
  112 | #include "cyclone/types.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
;; #> ../tmp/main 
win
;; #> cat ../tmp/main.scm ../tmp/foobar/base.sld ../tmp/foobar/body.scm 
(import (scheme base))
(import (scheme write))
(import (foobar base))


(display foobar)(newline)
(define-library (foobar base)
  (export foobar)
  (import (scheme base))

  (cond-expand
   (cyclone
    (include "body.scm"))
   (else
    (include "fuuuuu"))))
(define foobar "win")
;; #> 
```

**Comment by amirouche** [comment]
Oops! I cleaned up the `../tmp/` directory, and now the c compiler is really angry:

```
;; #> ./cyclone -COPT '-Iinclude' -CLNK '-L.' -A . -A ../tmp/ ../tmp/main.scm 
../tmp//foobar/base.c:112:10: fatal error: cyclone/types.h: No such file or directory
  112 | #include "cyclone/types.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
/usr/bin/ld: cannot find ../tmp//foobar/base.o: No such file or directory
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find .//foobar/base.o: No such file or directory
collect2: error: ld returned 1 exit status
;; #> 
```

**Comment by amirouche** [comment]
After `make bootstrap`, then inside `cyclone-bootstrap`:

```
make clean
make 
make install
```

It works :grimacing:

**Comment by justinethier** [comment]
Merged - thanks!

**Pull request closed without merging**
