### PR TITLE
Adding tests for SRFI 60

### PR DESCRIPTION
**Pull request by kozross**
I wasn't sure how to change the makefile, or to do a proper compile-and-run (I had trouble linking to SRFI 60, as I don't have the latest from git installed). Thus, I apologize for any errors.

### CODE REVIEW

**Comment by justinethier** [comment]
Everything is setup in cyclone-bootstrap on master if you want to pull from there and rebuild.

The tests do not run as-is:

    justin@justin-desktop:~/Documents/cyclone/tests$ cyclone  srfi-60-tests.scm
    Error: too many forms in do iterator: (if (= i j) 0 (+ 1 j))
    Call history:
    scheme/cyclone/util.sld:env:define-variable!
    scheme/cyclone/util.sld:env:first-frame
    scheme/cyclone/util.sld:env:frame-variables
    scheme/cyclone/util.sld:env:frame-values
    scheme/cyclone/util.sld:env:add-binding-to-frame!
    scheme/base.sld:map
    scheme/base.sld:foldr
    scheme/base.sld:error
    scheme/base.sld:raise

**Comment by kozross** [comment]
I'm currently having trouble getting ``make test`` to even compile this at all - I still get issues linking in SRFI 60 properly, even after adding the appropriate name to $(TESTSCM).

**Comment by justinethier** [comment]
Are you getting:

    Error: Unable to open file: "/usr/local/share/cyclone/srfi/60.sld"

If so, fetch the latest version of cyclone-boostrap on master and do a fresh build `sudo make clean ; ./install.sh` to make sure everything is installed properly.

**Comment by kozross** [comment]
Will this actually overwrite the system Cyclone I have installed? If so, that's something I'd rather not have to do if possible.

Also, do I need to fetch cyclone-bootstrap into the same directory as cyclone, or the parent directory of cyclone?

**Comment by justinethier** [comment]
Both repos should be cloned into directories under the same parent dir:

    /parent
    - cyclone
    - cyclone-bootstrap

You could also compile the SRFI and manually copy the files `60.o`, `60.scm`, and `60.sld` to `/usr/local/share/cyclone/srfi/`.

**Comment by kozross** [comment]
I think this *really* ties into #165 - having to replace the system install of Cyclone is pretty undesirable for cases like this IMHO.

**Comment by justinethier** [comment]
I agree... it would be much better if everything could be tested with a local copy of cyclone. Let me see what can be done.

**Comment by kozross** [comment]
I would say it's pretty damn vital. In-tree tests are an important part of proper packaging, and generally a good thing to do. It'd also make the Travis CI setup much simpler.

**Pull request merged**
