### PR TITLE
Add FreeBSD and AArch64 Linux to Travis CI

### PR DESCRIPTION
**Pull request by ararslan**
Also move the Homebrew package installation on macOS to the `homebrew` addon.

### CODE REVIEW

**Comment by ararslan** [comment]
The Travis status doesn't seem to be showing up; perhaps the webhook was disabled? The build is running: https://travis-ci.org/github/justinethier/cyclone/builds/722551563. If you're no longer using Travis for CI, it could be worthwhile to disable builds.

**Comment by ararslan** [comment]
And now builds aren't being triggered? 🤨

**Comment by justinethier** [comment]
Thanks @ararslan ! 

I would really like to get FreeBSD builds to work. Looks like there is some kind of syntax problem, trying to see if I can get everything to work. Always kind of a pain getting these CI scripts to work (but its great once they do).

**Comment by justinethier** [comment]
Thanks @ararslan ! Looks like we are good to go with these builds. I did need to disable the OSX builds to get everything to work. Not ideal but we have Github CI setup that handles them anyway, so it is not critical that Travis handle them. It is more important to get a wider range of CI platforms.

**Comment by ararslan** [comment]
I wonder why the Mac builds aren't working on Travis... I also wasn't able to build Cyclone via the Homebrew formula on macOS but haven't had time yet to figure out what the problem is there.

**Comment by justinethier** [comment]
@ararslan I think its just a matter of getting everything working properly with `gmake` across all existing platforms as well as OSX. Not "hard" to do, but rather tedious doing the trial-and-error necessary to get the Travis script working. I could be doing it wrong; since I don't have a dedicated OSX platform on this end I need to do more brute force / trial-and-error.

Homebrew builds are working through Github CI: https://github.com/justinethier/cyclone-bootstrap/blob/master/.github/workflows/ci-macos-brew.yml

Anyway, would be happy to take a pull request for it :)

**Pull request merged**
