### PR TITLE
Successfuly installed and tested Cyclone on FreeBSD 12.0 with clang 6…

### PR DESCRIPTION
**Pull request by arthurmaciel**
….0.1. Updated docs, adaptaed sync.sh and corrected Makefile

### CODE REVIEW

**Comment by lassik** [comment]
I'm also a BSD fan. Is it stable enough to make a port yet?

**Comment by arthurmaciel** [comment]
> I'm also a BSD fan. Is it stable enough to submit it to the official FreeBSD ports collection yet?

lassik, these patches only provide minimal adaptation of original Cyclone files. So they are as stable as Cyclone itself. The use of clang instead of gcc is somewhat a  concern, but only repeated warnings were presented and all tests passed. Could you test it on your preferred BSD? If ok for Justin and if it works for you I see no reason why we shouldn't provide a port pkg.

**Comment by lassik** [comment]
I can :)

**Comment by justinethier** [comment]
This is great, thanks @arthurmaciel !

**Pull request merged**
